trigger:
- main

pool:
  name: RanaRaad-pool
  demands:
    - agent.name -equals ranaraad-agent

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'RanaRaad-ServiceConnection'
    appType: 'webApp'
    appName: 'RanaRaad-WebApp'
    deployToSlotOrASE: true
    resourceGroupName: 'RanaRaad-RG'
    package: '$(System.DefaultWorkingDirectory)/build'
  displayName: 'Azure Web App Deploy: RanaRaad-WebApp'